# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_predict = QtWidgets.QPushButton(self.centralwidget)
        self.Button_predict.setGeometry(QtCore.QRect(290, 390, 191, 41))
        self.Button_predict.setObjectName("Button_predict")
        self.IW = QtWidgets.QLabel(self.centralwidget)
        self.IW.setGeometry(QtCore.QRect(120, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.IW.setFont(font)
        self.IW.setObjectName("IW")
        self.IF = QtWidgets.QLabel(self.centralwidget)
        self.IF.setGeometry(QtCore.QRect(280, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.IF.setFont(font)
        self.IF.setObjectName("IF")
        self.VW = QtWidgets.QLabel(self.centralwidget)
        self.VW.setGeometry(QtCore.QRect(450, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.VW.setFont(font)
        self.VW.setObjectName("VW")
        self.FP = QtWidgets.QLabel(self.centralwidget)
        self.FP.setGeometry(QtCore.QRect(630, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FP.setFont(font)
        self.FP.setObjectName("FP")
        self.labelIW = QtWidgets.QLineEdit(self.centralwidget)
        self.labelIW.setGeometry(QtCore.QRect(90, 220, 113, 22))
        self.labelIW.setObjectName("labelIW")
        self.labelIF = QtWidgets.QLineEdit(self.centralwidget)
        self.labelIF.setGeometry(QtCore.QRect(240, 220, 113, 22))
        self.labelIF.setObjectName("labelIF")
        self.labelVW = QtWidgets.QLineEdit(self.centralwidget)
        self.labelVW.setGeometry(QtCore.QRect(410, 220, 113, 22))
        self.labelVW.setObjectName("labelVW")
        self.labelFP = QtWidgets.QLineEdit(self.centralwidget)
        self.labelFP.setGeometry(QtCore.QRect(580, 220, 113, 22))
        self.labelFP.setObjectName("labelFP")
        self.labeltext = QtWidgets.QLabel(self.centralwidget)
        self.labeltext.setGeometry(QtCore.QRect(200, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labeltext.setFont(font)
        self.labeltext.setObjectName("labeltext")
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(250, 300, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer.setFont(font)
        self.answer.setText("")
        self.answer.setObjectName("answer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Итоговый проект"))
        self.Button_predict.setText(_translate("MainWindow", "Сделать прогноз"))
        self.IW.setText(_translate("MainWindow", "IW"))
        self.IF.setText(_translate("MainWindow", "IF"))
        self.VW.setText(_translate("MainWindow", "VW"))
        self.FP.setText(_translate("MainWindow", "FP"))
        self.labelIW.setText(_translate("MainWindow", "0"))
        self.labelIF.setText(_translate("MainWindow", "0"))
        self.labelVW.setText(_translate("MainWindow", "0"))
        self.labelFP.setText(_translate("MainWindow", "0"))
        self.labeltext.setText(_translate("MainWindow", "Введите значения признаков"))
